POST http://localhost:3000/permissions/check HTTP/1.1
x-cs-version: v1
x-cs-tenant: f737c736-b3d3-4eb0-bbf8-d368338bc72c
x-cs-user: 	712141d1-9bf4-42fc-ad1a-436a6f0c7d99

{
    "items": [
        {
            "domain": "*",
            "type": "user",
            "id": "*",
            "action": "read"
        },
        {
            "domain": "1234",
            "type": "project",
            "id": "100",
            "action": "read"
        }
    ]
}

###

GET http://localhost:3000/permissions/implicit?domain=* HTTP/1.1
x-cs-version: v1
x-cs-tenant: f737c736-b3d3-4eb0-bbf8-d368338bc72c
x-cs-user: 	712141d1-9bf4-42fc-ad1a-436a6f0c7d99

###

GET http://localhost:3000/permissions/assignments?domain=* HTTP/1.1
x-cs-version: v1
x-cs-tenant: f737c736-b3d3-4eb0-bbf8-d368338bc72c
x-cs-user: 	712141d1-9bf4-42fc-ad1a-436a6f0c7d99
